# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# https://github.com/python/black#version-control-integration
repos:
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy